spring.application.name=url-shortener-app
spring.datasource.url=jdbc:postgresql://localhost:5432/shortener
spring.datasource.username=postgres
spring.datasource.password=lolalana
spring.jpa.hibernate.ddl-auto=update
